# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-760ef259-079d-469a-b54a-b563106e2dd0";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-760ef259-079d-469a-b54a-b563106e2dd0".device = "/dev/disk/by-uuid/760ef259-079d-469a-b54a-b563106e2dd0";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6EC6-0059";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-bd45f143-16fe-4860-ada1-c4ec34c7ac11"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
